NOT_FOUND_RESPONSE = "$-1\r\n"
NIL_RESPONSE = "+nil\r\n"
SYNTAX_ERROR = "-ERR syntax error\r\n"
WRONG_TYPE_RESPONSE = "-WRONGTYPE Operation against a key holding the wrong kind of value\r\n"
NON_INT_ERROR = "-ERR value is not an integer or out of range\r\n"
EMPTY_ARRAY_RESPONSE = "+(empty array)"
OUT_OF_RANGE_RESPONSE = "+ERR index out of range"
FLOAT_ERROR_MESSAGE = "-ERR value is not a valid float\r\n"